name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -Rf ${JAVA_HOME_8_X64}
          sudo rm -Rf ${JAVA_HOME_11_X64}
          sudo rm -Rf ${JAVA_HOME_17_X64}
          sudo rm -Rf ${RUBY_PATH}
      - uses: actions/checkout@v4
      - name: Get the dump
        run: |
          curl --retry 50 --retry-max-time 3600 -sSL https://trustify-dumps.s3.eu-west-1.amazonaws.com/20250323T044433Z/dump.sql.gz -o dump.sql.gz
          gzip -d dump.sql.gz
      - name: Download and extract trustify-pm
        run: |
          curl -L -o trustd-pm.tar.gz https://github.com/trustification/trustify/releases/download/v0.2.14/trustd-pm-0.2.14-x86_64-unknown-linux-gnu.tar.gz
          tar xzf trustd-pm.tar.gz --strip-components=1
      - name: Download and extract hurl
        run: |
          curl -L -o hurl.tar.gz https://github.com/Orange-OpenSource/hurl/releases/download/6.1.1/hurl-6.1.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf hurl.tar.gz --strip-components=2
      - name: Run trustify pm-mode
        run: |
          AUTH_DISABLED=true ./trustd-pm &
          until curl --output /dev/null --silent --head --fail http://localhost:8080; do
            echo "Waiting for trustd-pm..."
            sleep 2
          done
      - name: Dump restore
        run: .github/scripts/restore.sh
      - name: Dataset test
        run: |
          ./hurl --test --variables-file .env hurls/dataset/uploadDataset.hurl
      - name: Run the tests
        run: |
          ./hurl --test --variables-file .env hurls/*.hurl
      - name: Stop trustify pm-mode
        run: |
          killall trustd-pm
