name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download and extract trustify-pm
        run: |
          curl -L -o trustd-pm.tar.gz https://github.com/trustification/trustify/releases/download/v0.2.2/trustd-pm-0.2.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf trustd-pm.tar.gz --strip-components=2
      - name: Download and extract hurl
        run: |
          curl -L -o hurl.tar.gz https://github.com/Orange-OpenSource/hurl/releases/download/6.0.0/hurl-6.0.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf hurl.tar.gz --strip-components=2
      - name: Run trustify pm-mode
        run: |
          AUTH_DISABLED=true ./trustd-pm &
          until curl --output /dev/null --silent --head --fail http://localhost:8080; do
            echo "Waiting for trustd-pm..."
            sleep 2
          done
      - name: Dataset test
        run: |
          ./hurl --test --variables-file .env hurls/dataset/uploadDataset.hurl
      - name: Run the tests
        run: |
          ./hurl --test --variables-file .env hurls/*.hurl
      - name: Stop trustify pm-mode
        run: |
          killall trustd-pm
