name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -Rf ${JAVA_HOME_8_X64}
          sudo rm -Rf ${JAVA_HOME_11_X64}
          sudo rm -Rf ${JAVA_HOME_17_X64}
          sudo rm -Rf ${RUBY_PATH}
      - uses: actions/checkout@v4
      - name: Get the dump
        run: |
          curl --retry 50 --retry-max-time 3600 -sSL https://trustify-dumps.s3.eu-west-1.amazonaws.com/20250323T044433Z/dump.sql.gz -o dump.sql.gz
          gzip -d dump.sql.gz
      - name: Download and extract trustify-pm
        run: |
          curl -L -o trustd-pm.tar.gz https://github.com/trustification/trustify/releases/download/v0.2.17/trustd-pm-0.2.17-x86_64-unknown-linux-gnu.tar.gz
          tar xzf trustd-pm.tar.gz --strip-components=1
      - name: Download and extract hurl
        run: |
          curl -L -o hurl.tar.gz https://github.com/Orange-OpenSource/hurl/releases/download/6.1.1/hurl-6.1.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf hurl.tar.gz --strip-components=2
      - name: Run trustify pm-mode
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          AUTH_DISABLED=true ./trustd-pm &
          until curl --output /dev/null --silent --head --fail http://localhost:8080; do
            echo "Waiting for trustd-pm..."
            sleep 3
          done
      # - name: Dump restore
      #   run: .github/scripts/restore.sh
      - name: Cache Theseus Postgresql Installation
        uses: actions/cache@v4
        with:
          path: ~/.theseus/postgresql
      - name: Stop trustify pm-mode
        run: killall trustd-pm
      # - name: Run trustify pm-mode (again)
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #   run: |
      #     AUTH_DISABLED=true ./trustd-pm &
      #     until curl --output /dev/null --silent --head --fail http://localhost:8080; do
      #       echo "Waiting for trustd-pm..."
      #       sleep 3
      #     done
      # - name: Test - list
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/list*.hurl
      # - name: Test - get
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/get*.hurl
      # - name: Test - update
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/update*.hurl
      # - name: Test - upload
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/upload*.hurl
      # - name: Test - patch
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/patch*.hurl
      # - name: Test - other
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/analyze.hurl h/countRelatedSboms.hurl h/createImporter.hurl h/downloadAdvisory.hurl h/downloadSbom.hurl h/enableImporter.hurl h/forceRunImporter.hurl h/info.hurl h/renderSbomGraph.hurl h/searchComponent.hurl h/searchLatestComponent.hurl h/setUserPreferences.hurl h/status.hurl
      # - name: Test - delete
      #   run: |
      #     ./hurl --test --jobs 1 --variables-file .env h/delete*.hurl
      # - name: Stop trustify pm-mode
      #   run: |
      #     killall trustd-pm
